# Generated by Django 4.2.11 on 2025-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transmisstion', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cv', 'Continiously Variable')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=50)),
                ('license_plate', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Super car', 'Super car')], max_length=100)),
                ('description', models.TextField()),
                ('images_url', models.JSONField(blank=True, default=list)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
