# Generated by Django 4.2.11 on 2025-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='color',
            field=models.JSONField(default=list),
        ),
    ]
