# Generated by Django 4.2.11 on 2025-10-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0002_alter_carmodel_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='transmisstion',
            new_name='transmission',
        ),
    ]
