# Generated by Django 5.2.7 on 2025-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0003_rename_transmisstion_carmodel_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='images_url',
            field=models.JSONField(default=list),
        ),
    ]
