# Generated by Django 5.2.7 on 2025-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0004_alter_carmodel_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
