# Generated by Django 5.2.7 on 2025-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0005_alter_carmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='license_plate',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
