# Generated by Django 5.2.7 on 2025-10-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carproduct', '0006_alter_carmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
