import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Car Rental App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
        <Toaster richColors closeButton position="top-right"/>
      </body>
    </html>
  );
}
