"""
Django settings for CarRentalBackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u%o(d)tn)nt%6jjh@mjx0njsqtr7txaf8c6est+fe%ay23fijg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djoser',
    'rest_framework_simplejwt',
    'corsheaders',
    'authentication',
    'carproduct'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    # 'http://127.0.0.1:5500',
    'http://127.0.0.1:5000',
    "http://127.0.0.1:5500",
    "http://localhost:5500",

]
ROOT_URLCONF = 'CarRentalBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CarRentalBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    # Switch back to postgresql for deployment or testing
    # 'default': {
    #     'ENGINE':'django.db.backends.postgresql',
    #     'USER':"postgres.ctibysukgdkjvwyaaojs",
    #     'PASSWORD':'teamshopifypostgresql',
    #     'HOST':'aws-1-us-east-2.pooler.supabase.com',
    #     'PORT':'6543',
    #     'NAME':'postgres'
    # }

    # Using sqlite for development
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mypostgresql_2qm5',
        'USER': 'battleangel',
        'PASSWORD': '0LpfajdGL3WezzDZu3MdIZoS9K21TBcn',
        'HOST' : 'dpg-d38lcqmmcj7s738elspg-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}


DATABASES["default"]["OPTIONS"] = {
    "options": "-c search_path=test_carrental"
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        
    ]
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=5)
}

AUTH_USER_MODEL = 'authentication.CustomUserModel'

AUTHENTICATION_BACKENDS = [
    'authentication.backend.LoginBackend',
    'django.contrib.auth.backends.ModelBackend',
]

DJOSER = {
    'USER_ID_FIELD':'id',
    'LOGIN_FIELD':'username',
    'SERIALIZERS':{
        'user':'authentication.serializers.CustomUserSerializer',
        'user_create':'authentication.serializers.CustomUserCreateSerializer',
        'token_create':'authentication.serializers.CustomTokenCreateSerializer'
    },
}

SUPABASE_URL = "https://dfansamuqoojcgujsyxd.supabase.co"
SUPABASE_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYW5zYW11cW9vamNndWpzeXhkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTgyNjc2MywiZXhwIjoyMDc1NDAyNzYzfQ.J-oM5WRFLLhjn5nWUgWvXIPjCx5QZ3KBcb2GQ0x7Ssw"