# Generated by Django 5.2.7 on 2025-10-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='expire_date',
            new_name='expiry_date',
        ),
    ]
