# Generated by Django 5.2.7 on 2025-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0002_rename_expire_date_reservationmodel_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('soft', 'soft'), ('firm', 'firm'), ('expired', 'expired'), ('deleted', 'deleted'), ('completed', 'completed')], max_length=10),
        ),
    ]
