# Generated by Django 5.2.7 on 2025-10-20 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0003_alter_reservationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
