# Generated by Django 5.2.7 on 2025-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0004_reservationmodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='end_dat',
            field=models.DateField(null=True),
        ),
    ]
