# Generated by Django 5.2.7 on 2025-10-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0005_reservationmodel_end_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='end_dat',
            new_name='end_date',
        ),
    ]
