# Generated by Django 5.2.7 on 2025-10-20 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reservation', '0006_rename_end_dat_reservationmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
